AIRPACT_Fire/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from user_profile import views as user_view
from convos import views as convos_view
from file_upload import views as file_upload_views
from django_comments.models import Comment
from . import views
from .views import LocationAutocomplete
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	url(r'^$', views.index, name="home"),
    url(r'^tag-autocomplete/$', LocationAutocomplete.as_view(), name='location-autocomplete'),
    url(r'^admin_page$', views.admin_page, name="adminPage"),
    url(r'^uncertified$', views.uncertified, name="uncertified"),
    url(r'^user/', include('user_profile.urls')),
   #url(r'^user', include('user_profile.urls')),
    url(r'^gallery/$', views.gallery, name="gallery"),
    url(r'^gallery/(?P<page>\d+)/$', views.gallery, name='gallery'),
    url(r'^test$', views.test),
	url(r'^file_upload/', include('file_upload.urls')),
    url(r'^admin/', admin.site.urls), 
    url(r'^picture/view/(?P<picId>\d+)/$', file_upload_views.view_picture, name="view_picture"),
    #url(r'^convos/([0-9]+)/$', convos_view.render_convo),
    #url(r'^comments/post/$', convos_view.comment_post),
    #url( r'^comments/posted/$', convos_view.comment_posted),    
    url(r'^comments/', include('django_comments.urls')),
    url(r'^downloads/', views.downloads, name="downloads"),
    url(r'^about/',views.about,name="about"),
    url(r'^index/',views.main,name="main"),
    url(r'^forum/',include('spirit.urls'), name="forum"),
    url(r'^getPythonScripts/', views.getPythonScripts, name="getPythonScripts"),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

file_upload/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload$', views.upload, name='upload'),
    url(r'^test$',views.test, name='test'),
    url(r'^delete/(?P<id>\d+)/$',views.delete_picture, name="delete_picture")
]

user_profile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^admin_page$', views.admin_page, name="adminPage"),
    url(r'^$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^auth$', views.auth_view),
    url(r'^register$', views.register_user, name='register'),
    url(r'^loggedin$', views.loggedin),
    url(r'^invalid$', views.invalid_login),
    url(r'^appauth$',views.user_app_auth),
    url(r'^register_success$', views.register_success),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^profile/manage_pictures/$', views.manage_pictures, name="manage_pictures"),
    url(r'^profile/(?P<name>[-A-Za-z]+)/$', views.view_profile, name="view_profile"),
    url(r'^profile/(?P<name>[-A-Za-z]+)/(?P<page>\d+)/$', views.view_profile, name="view_profile"),
    
    #include('file_upload.urls')
    #more to come...
]

convos/models.py
from __future__ import unicode_literals
from django.db import models
from file_upload.models import picture
from user_profile.models import AirpactUser


# The model responsible for storing information about the convo page
class convoPage(models.Model):	 
	picture = models.ForeignKey(picture, on_delete=models.CASCADE)	
	description = models.TextField(default = "", blank = True)
	
	def __str__(self):
		return self.description



# a custom comments class! whoo! It has convo page
class comment(models.Model):
	convoPage = models.ForeignKey(convoPage, on_delete=models.CASCADE)
	text =  models.TextField(default = "", blank = True)

	def __str__(self):
		return self.description	

user_profile/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import (
	AbstractBaseUser, BaseUserManager)




# Define custom User manager. 
class AirpactUserManager(BaseUserManager):
	
	# define custom create user 
	def create_user(self, email, username, password = None):
		if not email:
			raise ValueError('Users must have valid email')

		if not username:
			raise ValueError('Users must have a name!')

		if not password:
			raise ValueError('Users must have a valid password!')

		user = self.model(username=username)
		user.set_password(password)
		user.save(using=self._db)

		return user

	# I believe a super user is a user with admin priviledges
	def create_superuser(self,username, email, password):
		user = self.create_user(email=email, username = username, password = password)
		user.is_admin = True;
		user.is_superuser = True;
		user.save(using=self._db)

		return user


# This is a custom user/userprofile class
class AirpactUser(AbstractBaseUser):
	username = models.CharField(max_length=254, unique=True)
	#password = models.CharField(max_length=254)
	bio = models.TextField(max_length=1000, null=True, blank=True)
	first_name = models.CharField(max_length=30,null=False, blank=True)
	last_name = models.CharField(max_length=30, null=False, blank=True)
	email = models.EmailField(blank=True)
	is_custom_admin = models.BooleanField(default = False)
	is_certified = models.BooleanField(default = False)
	is_superuser = models.BooleanField(default = False)
	bob = models.BooleanField(default= False)
	objects = AirpactUserManager()

	#required to implement
	is_active = models.BooleanField(default=True)

	#required to implement
	USERNAME_FIELD = 'username'
   	
   	#TODO: make this a longer list, required to implement
   	REQUIRED_FIELDS = ['email']

   	def get_full_name():
   		return (first_name + last_name)

   	def get_short_name():
   		return first_name

class AuthToken(models.Model):
	token = models.TextField(max_length =22, unique=True, primary_key=True)
	issue_date = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.token

user_profile/forms.py
from django import forms
import re
from django.contrib.auth.forms import ReadOnlyPasswordHashField            
from django.contrib.auth.models import User   # fill in custom user info then save it 
from user_profile.models import AirpactUser    
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

def usernameValidator(value):
    pattern = re.compile("^[a-zA-Z]*$")
    return pattern.match(value)
 

# Custom user creation form for an Airpact User
class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='confirm password', widget=forms.PasswordInput)
    class Meta:
        model = AirpactUser

        # Note - include all *required* MyUser fields here,
        # but don't need to include password and confirm_password as they are
        # already included since they are defined above.
        fields = ('username','email')       

    def clean(self):
        print(self.cleaned_data)
        if not usernameValidator(self.cleaned_data.get('username')):
            self.add_error('username', 'Username contains invalid characters. Usernames may only contain letters')
        if'password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                self.add_error('confirm_password', 'Password & Confirm Password must match.')

        return super(UserCreationForm, self).clean()

    def cleanUsername(self):
        if not usernameValidator(self.cleaned_data.get('username')):
            self.add_error('username', 'Username contains invalid characters. Usernames may only consist of letters')

    def save(self,commit = True):   
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.email = self.cleaned_data['email']
        
        # Fields to be added later: 
        #user.first_name = self.cleaned_data['first_name']
        #user.last_name = self.cleaned_data['last_name']
    
        if commit:
            user.save()
        return user

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = AirpactUser
        fields = ['first_name', 'last_name', 'email','bio']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'})
        }

convos/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
# Standard import things
from django.shortcuts import render
from django.http import HttpResponse
from file_upload.models import picture
from file_upload.models import tag
from user_profile.models import AuthToken
from user_profile.models import AirpactUser
from file_upload.forms import picture_upload_form
from convos.models import convoPage
from django.contrib.auth.decorators import login_required


# Don't use this!  
def render_convo(request, convo_id):
	convo = convoPage.objects.get(id=convo_id)
	picture = convo.picture
	pictures = None
	cur_tag = tag.objects.get(picture= picture)
	#Entry.objects.all()[5:10]
	print("\n This is the current_tag: ")
	print(cur_Tag + "\n") 

	# If we are loading all of the pictures, yo. 
	if request.method == 'POST':
		print("Blah\n");



	return render_to_response(
    'convos.html',
    {'picture': picture, 'pictures':pictures, 
    'convos':convo, 'convo_id':convo_id, 'theURL':'/picture/view/'+convo_id+'/', 'tag':tag },
    context_instance=RequestContext(request))	


# Overrides comment posted
def comment_post(request):
	print("I am at comment post, this is request: \n\n")
	print(request.url)
	return HttpResponseRedirect( "/" )
	

user_profile/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from user_profile.models import AirpactUser
from user_profile.models import AuthToken
from file_upload.models import picture
from django.template import RequestContext
from forms import UserCreationForm
from forms import EditProfileForm
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import logout
from convos.models import convoPage
import json
import random
import string

@login_required
def user_profile(request):
	if request.user.is_certified is False:
		return render_to_response('not_certified.html')
	if(request.method == 'POST'):
		form = UserProfileForm(request.POST, instance=request.user.profile)

def login(request):
	c = {}
	c.update(csrf(request))
	return render_to_response('login.html', c)

@login_required
def logout(request):
	auth.logout(request)
	c = {}
	c.update(csrf(request))
	return render_to_response('login.html', c)

def auth_view(request):
	if(request.method == 'POST'):
		username = request.POST['username']
		password = request.POST['password']
		user = auth.authenticate(username=username, password=password)

	# # For now, do not ask for the email
	# #email = request.POST['email']

	# print("\n ! !  This is the post information from login:")
	# print(request.POST)
	# print("\n ! !  This is the password:")
	# print(password)


		if user is not None:
		   auth.login(request, user)
		   return HttpResponseRedirect("/user/profile/"+ user.username + "/1")
		else:
			return render_to_response('login.html',  {'Errors':"Invalid username or Password"}, context_instance=RequestContext(request) )
	return HttpResponse("DONT GO HERE")
	
def loggedin(request):
	return render_to_response('loggedin.html')

def invalid_login(request):
	return render_to_response('invalid.html')


# Register/ Create a new user
def register_user(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/user/')
		else:
			return render_to_response('register.html',  {'form':form}, context_instance=RequestContext(request) )
	form = UserCreationForm()
	return render_to_response('register.html',  {'form':form}, context_instance=RequestContext(request) )


def register_success(request): 
	return render_to_response('register_success.html', {'message': "successfull registration! "}, context_instance=RequestContext(request))

@csrf_exempt
def user_app_auth(request):
	if request.method == 'POST':
		userdata = json.loads(request.body)
		print(userdata['username'])
		print(userdata['password'])
		user = auth.authenticate(username=userdata['username'], password=userdata['password'] )
		response_data = {}
		if user is not None and user.is_certified:
			#generate secret key
			secret = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(22))
			secretKey = AuthToken(token = secret)
			secretKey.save()
			response_data['isUser'] = 'true'
			response_data['secretKey'] = secret
		else:
			response_data['isUser'] = 'false'
			response_data['secretKey'] = ''
		print(json.dumps(response_data))
		return HttpResponse(json.dumps(response_data), content_type="application/json")
	else:
		return HttpResponse("HI")


def view_profile(request, name, page = 1):
	# we need to get the current user info
	# send it to the view...so lets do that I guess
	thisuser = False
	if request.user.username == name:
		thisuser = True
	user = AirpactUser.objects.get(username = name)
	userpictures = picture.objects.filter(user = user)
	paginator = Paginator(userpictures, 12) #show 12 per page
	try:
		pictures = paginator.page(page)
	except PageNotAnInteger:
		pictures = paginator.page(1)
	except EmptyPage:
		pictures = paginator.page(paginator.num_pages)
	return render_to_response('user_profile.html', {'pictures' : pictures, 'profile_user':user, 'thisuser':thisuser}, context_instance=RequestContext(request))

@login_required
def edit_profile(request):
	if request.user.is_certified is False:
		return render_to_response('not_certified.html')

	userob = AirpactUser.objects.get(username=request.user.username)
	if request.method == 'POST':
		# do stuff to save the new user data
		form = EditProfileForm(request.POST)
		if form.is_valid():
			userob.first_name = form.cleaned_data.get('first_name')
			userob.last_name = form.cleaned_data.get('last_name')
			userob.email = form.cleaned_data.get('email')
			userob.bio = form.cleaned_data.get('bio')
			userob.save()
		#reidrect back to their profile
		return HttpResponseRedirect('/user/profile/'+request.user.username+'/')
	form = EditProfileForm(instance=userob)
	pictures = picture.objects.filter(user = userob)
	return render_to_response('edit_profile.html', {'user': request.user, 'form':form, 'pictures': pictures}, context_instance=RequestContext(request))

@login_required
def manage_pictures(request):
	userob = AirpactUser.objects.get(username=request.user.username)
	pictures = picture.objects.filter(user= userob)
	return render_to_response('manage_pictures.html', {'pictures': pictures}, context_instance=RequestContext(request))


@csrf_exempt
@login_required
def admin_page(request):
	if request.user.is_custom_admin is False:
		return HttpResponseRedirect('/')
	if request.user.is_certified is False:
		return render_to_response('not_certified.html')

	nusers = AirpactUser.objects.all()
	if(request.method == 'POST'):
		print(request.POST)
		username = request.POST.get("ourUser",False)
		nuser = AirpactUser.objects.get(username=username)
		the_type = request.POST['the_type']
		
		if(the_type == "certify"):
			nuser.is_certified = True 
			nuser.save()

		if(the_type == "uncertify"):
			nuser.is_certified = False 
			nuser.save()

		if(the_type == "make_admin"):
			nuser.is_custom_admin = True
			nuser.save() 

		if(the_type == "unmake_admin"):
			nuser.is_custom_admin = False
			nuser.save() 

		if(the_type == "delete"):
			nuser.delete()

	return render_to_response('custom_admin_page.html', {'nusers': nusers}, context_instance=RequestContext(request));

templates/convos.html
{% extends "base/newbase.html" %}
{% load comments %}
{% block airpact-content %}

	<div class="col-lg-9">
		<p><img  class="img-responsive" src="{{ picture.pic.url }}" alt="{{ picture.pic.url}}" align = "middle" id ="mainPicture" /> </p>
		<p> Click Image for Timeline slideshow </p> <button id="sampleToggle"> Toggle Sampled Pixels Overlay </button>
	</div>
	<div class="col-lg-3"> 
		<table class="table table-striped">
			<tr>
				<td> Estimated Visual Range </td>
				<td> {{ picture.vr }} </td>
			</tr>
			<tr>
				<td> Computed Visual Range </td>
				<td> {{ picture.twoTargetContrastVr }}
			</tr>
			<tr>
				<td> User </td>
				<td> <a href="{% url 'view_profile' name=picture.user %}"> {{ picture.user }} </a> </td>
			</tr>
			<tr>
				<td> Description </td>
				<td> {{ picture.description }} </td>
			</tr>
			<tr>
				<td> Location </td>
				<td> {{ tag.text }} </td>
			</tr>
		</table>
	</div>
	<div class="col-lg-2"> 
	</div>


	<div class="col-lg-12">
		<a name="comment_start"></a>

		<div class = "comment_form">

			{% if user.is_authenticated %}
			{% get_comment_form for convos as form %}
			<form action = "{% comment_form_target %}" method="POST">
			{% csrf_token %}


			{{ form.comment }}


			{{ form.content_type }}
			{{ form.object_pk }}
			{{ form.timestamp }}
			{{ form.security_hash }}


			<input type ="hidden" name="name" value = "{{ user }}">
			<input type ="hidden" name="email" value = "nothing@gmail.com">
			<input type ="hidden" name="url" value = "https://www.nothing.com">

			<input type = "hidden" name = "next" value="/picture/view/{{ picture.id }}#comment_start">
			<p><input type = "submit" value= "Add comment" id="id_submit" /></p>
			</form>

			{% else %}

			<p> Please log in to comment </p>

			{% endif %}
		</div>

		<H2 class="col-lg-12">Comments: </H2>


		{% get_comment_list for convos as comment_list %}
		{% for comment in comment_list reversed %}


		{% if comment.id|divisibleby:2 %}
		<div class = "col-lg-12 commentRow">
			<p class="col-lg-12 comment-header"> Posted by: {{ comment.user_name }} on {{ comment.submit_date }}</p>
			<strong><p class="col-lg-12">{{ comment.comment }} </p></strong>
		</div>	
		{% else %}
		<div class = "col-lg-12 commentRow2">
			<p class="col-lg-12 comment-header"> Posted by: {{ comment.user_name }} on {{ comment.submit_date }}</p>
			<strong><p class="col-lg-12">{{ comment.comment }} </p> </strong>
		</div>	
		{% endif %}


		{% endfor %}
	</div>
</div>


<!-- begin weird timeline slideshow stuff -->
<div class="slideShowContainer" id="slideShowContainer">
	<div id="slideShowMainPicture"> 
		<div id="slideShowBottomInfoPanel"> 
			<table class="table">
			<thead>
				<th> Date </th>
				<th> Location </th>
				<th> Visual Range </th>
				<th> Description </th>
			</thead>
			</tr>
				<td id="slideShowDate">{{ picture.uploaded }}</td>
				<td id="slideShowLocation"> {{tag.text}} </td>
				<td id="slideShowVr"> {{ picture.vr }}</td>
				<td id="slideShowDesc"> {{ picture.description }}</td>
			</tr>
			</table>
		</div>
	</div>
	<div id="slideShowLeftNavArrow"> </div>
	<div id="slideShowRightNavArrow"> </div>
</div>


<script type="text/javascript">

var sampleToggleState = 0;
var pictures = [];
var starting_index = 0;
var currentIndex = 0;
// FIX THIS, IT SHOULD BE A JSON OBJECT SENT FROM THE VIEW!!! (but it works for now :D )
{% for picture in pictures %}
	pictures.push(new picture ({{picture.id}}, "{{picture.uploaded}}",{{picture.vr}}, "{{picture.description}}", "{{picture.pic.url}}"));
{% endfor %}

function picture (id, date, vr, description, url){

	this.id = id;
	this.date = date;
	this.vr= vr;
	this.description = description;
	this.url = url;
}

function fadeScreen(){
	$('#overlay').slideDown( function(){ 	$("#slideShowContainer").fadeIn(); });

}

function fadeBack(){

	$('#slideShowContainer').fadeOut( function(){ 
		$("#overlay").slideUp(); 
		currentIndex=starting_index;
		$('#slideShowMainPicture').css('background-image', 'url('+String(pictures[currentIndex].url)+')');
	});
	

}
function findStartingIndex()
{
	var currentPicid = {{ picture.id }}
	for(var i = 0; i < pictures.length; i++)
	{
		if(currentPicid == pictures[i].id)
		{
			starting_index = i;
		}
	}
}
function moveLeft()
{
	if(currentIndex == 0)
	{
		currentIndex = pictures.length - 1;
	}
	else
	{
		currentIndex = currentIndex - 1;
	}

	$('#slideShowContainer').fadeOut(function(){
		$('#slideShowMainPicture').css('background-image', 'url('+String(pictures[currentIndex].url)+')');
		updateTable();
		$('#slideShowContainer').fadeIn(500);
	});
}
function moveRight()
{
	if(currentIndex == pictures.length-1)
	{
		currentIndex = 0;
	}
	else
	{
		currentIndex = currentIndex + 1;
	}

	$('#slideShowContainer').fadeOut(function(){
		$('#slideShowMainPicture').css('background-image', 'url('+String(pictures[currentIndex].url)+')');
		updateTable();
		$('#slideShowContainer').fadeIn(500);
	});
}

function updateTable()
{
	$('#slideShowDate').html(String(pictures[currentIndex].date));
	$('#slideShowVr').html(String(pictures[currentIndex].vr));
	$('#slideShowDesc').html(String(pictures[currentIndex].description));
}

function toggleSampleOverlay()
{
	if(sampleToggleState === 0)
	{
		$('#mainPicture').attr("src","{{ picture.pictureWithCircles.url }}");
		sampleToggleState = 1;
	}
	else
	{
		$('#mainPicture').attr("src","{{ picture.pic.url }}");
		sampleToggleState = 0;

	}
}

$(document).ready(function(){
	findStartingIndex();
	currentIndex=starting_index;
	$("#slideShowMainPicture").css('background-image', "url("+String(pictures[starting_index].url)+")");
	hidden = false;
	$('#mainPicture').click(function(){
		if (hidden == false)
		{
			fadeScreen();
			hidden=true;
		}
	});

	$('#overlay').click(function(){
		if(hidden == true)
		{
			fadeBack();
			hidden=false;
		}
	});
	$('#slideShowLeftNavArrow').click(function(){
		moveLeft();
	});
	$('#slideShowRightNavArrow').click(function(){
		moveRight();
	});


	$('#sampleToggle').click( function() {
		toggleSampleOverlay();
	});
});

</script>
{% endblock %}

templates/custom_admin_page.html
{% extends "base/newbase.html" %}
{% block airpact-content %}
<div class="col-md-7 col-md-offset-2">
<table class="table table-striped adminTable">
   <tr>
    <th> User Name </th>
    <th> Make Certified</th> 
    <th> Make Admin</th>
    <th> Delete</th>
  </tr>
  
  {% for u in nusers %}
  <tr>
    <td><strong>{{ u.username }}</strong></td>

    <td>
    {% if u.is_certified == False %}
	<form action = "{% url "adminPage" %}" method = "POST"> 
		<input type="hidden" name="the_type" value="certify">
		<input type="hidden" name="ourUser" value="{{ u.username }}"> 
		<input type="submit" class="btn btn-primary" value="Make Certified">
	</form>
	{% else %}

	<form action = "{% url "adminPage" %}" method = "POST"> 
		<input type="hidden" name="the_type" value="uncertify">
		<input type="hidden" name="ourUser" value="{{ u.username }}"> 
		<input type="submit" class="btn btn-warning" value="Make Uncertified">
	</form>
	{% endif %}
    </td>

    <td>
    {% if u.is_custom_admin == False %}
	<form action = "{% url "adminPage" %}" method = "POST"> 
		<input type="hidden" name="the_type" value="make_admin">
		<input type="hidden" name="ourUser" value="{{ u.username }}"> 
		<input type="submit" class="btn btn-primary" value="Make Admin">
	</form>
	{% else %}

	<form action = "{% url "adminPage" %}" method = "POST"> 
		<input type="hidden" name="the_type" value="unmake_admin">
		<input type="hidden" name="ourUser" value="{{ u.username }}"> 
		<input type="submit" class="btn btn-warning" value="Demote From Admin">
	</form>
	{% endif %}	
    </td>

     <td>
    
	<form action = "{% url "adminPage" %}" method = "POST"> 
		<input type="hidden" name="the_type" value="delete">
		<input type="hidden" name="ourUser" value="{{ u.username }}"> 
		<input type="submit" onclick="return confirm('Are you sure you wish to delete user?')" class="btn btn-danger" value="Delete User">
	</form>

    </td>

  </tr>
  {% endfor %}

</table>
</div>
{% endblock %}

templates/edit_profile.html
{% extends "base/newbase.html" %}
{% block airpact-content %}

<div class="col-lg-7">
	<h3> Edit Profile </h3>
	<form action="/user/profile/edit/" method="post">
			{% csrf_token %}
			{{ form }}
	<button type="submit" id="submit" class="btn btn-default"> Submit </button>
	</form>
</div>

{% endblock %}

templates/forum.html
{% extends "base/newbase.html" %}
{% block airpact-content %}
<h2 class="col-lg-12 "> Welcome! </h2>
	<p class= "col-lg-12"> 
		This page is currently under construction!
	</p>
{% endblock %}

templates/gallery.html
{% extends "base/newbase.html" %}
{% block airpact-content %}
<head>
  {{ form.media }}
</head>

<h1 class="col-lg-24">Gallery</h1>

<div id = "menu">
	<p><button type="submit" class="btn btn-info" >Show Search Features</button></p>
</div>

<div id = "collapsible" style="display:none">
	<div class="col-lg-12" style="padding-bottom: 5px;"> 
		<form class="form-inline" method="POST">
		Search by: <br/>
			{% csrf_token %}
			<div class="form-group">
			{{ form.as_table }}

		<button type="submit" class="btn btn-default"> Search </button>
	</div>		
		</form>
</div>


</div>
	{% for picture in pictures %}
		<div class="col-lg-3">
			<a href="{% url 'view_picture' picId=picture.id %}"> <img class="img-thumbnail" src="{{ picture.thumbnail.url }}" alt="{{ picture..url}}" /> </a>
			<div>
				<article> Date: {{ picture.uploaded }} </article>
				<div> VR: {{picture.vr }} </div>
				<article> uploaded by: <a href="{% url 'view_profile' name=picture.user %}"> {{ picture.user }} </a> </article>
				
			</div>
		</div>
	{% endfor %}

	<div class= "col-lg-12">
		<ul class="pagination">
			{% if pictures.number != 1 %}
				<li>
					<a href="{% url 'gallery' page=pictures.previous_page_number %}"> << </a>
				</li>
			{% endif %}
			{% if pictures.paginator.num_pages > 1 %}
				{% for num in pictures.paginator.page_range %}
					{% if pictures.number == num %}
						<li class="active"> <a href="" > {{num}}</a> </li>
					{% else %}
						<li> <a href="{% url 'gallery' page=num %}"> {{ num }} </a> </li>
					{% endif %}
				{% endfor %}
				{% if pictures.number != pictures.paginator.num_pages %}
					<li>
						<a href="{% url 'gallery' page=pictures.next_page_number %}"> >> </a>
					</li>
				{% endif %}
			{% endif %}

		</ul>
	</div>


<script>
$(function(){
	$('#date1').datepicker();
});
$(function(){
	$('#date2').datepicker();
});


$('#menu').click(function(){
    $(this).next().slideToggle();
    return false;
});

$('#menu').click(function(){
if ($.trim($(this).text()) === 'Show Search Features') {
    $(this).text('Hide Search Features');
} else {
    $(this).text('Show Search Features');        
}
   });

</script>
{% endblock %}

templates/list.html
<dl id="comments">
  {% for comment in comment_list %}
    <dt id="c{{ comment.id }}">
      {{ comment.submit_date }} - {{ comment.name }}
    </dt>
    <dd>
      <p>{{ comment.comment }}</p>
    </dd>
  {% endfor %}
</dl>